transactions(types: [APP_SUBSCRIPTION_SALE], after: $cursor, first: 100) {
        edges {
          cursor
          node {
            id,
            createdAt,
            ... on AppSubscriptionSale {
              netAmount {
                amount
              },
              app {
                name
              },
              shop {
                myshopifyDomain
              }
            },
            ... on ServiceSale {
              netAmount {
                amount
              },
              shop {
                myshopifyDomain
              }
            }
          }
        },
        pageInfo {
            hasNextPage
        }
      }
    }